apiVersion: v1
kind: Service
metadata:
  name: "{{ include "retail-app.name" . }}"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "retail-app.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Cluster
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "retail-app.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
