import {
  INITIATE_LOANS_PAYMENT_JOURNEY_PAYMENT_ORDER_A2A_BASE_PATH,
  INITIATE_LOANS_PAYMENT_JOURNEY_CONTACT_MANAGER_BASE_PATH,
  INITIATE_LOANS_PAYMENT_JOURNEY_PAYMENT_TEMPLATE_BASE_PATH,
  INITIATE_LOANS_PAYMENT_JOURNEY_ARRANGEMENT_MANAGER_BASE_PATH,
  INITIATE_LOANS_PAYMENT_JOURNEY_PAYMENT_ORDER_BASE_PATH,
  INITIATE_LOANS_PAYMENT_JOURNEY_PAYMENT_ORDER_OPTIONS_BASE_PATH,
  INITIATE_LOANS_PAYMENT_JOURNEY_ACCESS_CONTROL_BASE_PATH,
} from '@backbase/initiate-loans-payment-journey';
import {
  APP_ACCESS_CONTROL_BASE_PATH,
  APP_ARRANGEMENT_MANAGER_BASE_PATH,
  APP_CONTACT_MANAGER_BASE_PATH,
  APP_PAYMENT_ORDER_A2A_BASE_PATH,
  APP_PAYMENT_ORDER_BASE_PATH,
  APP_PAYMENT_ORDER_OPTIONS_BASE_PATH,
} from '../../../service-paths.module';

export const loanPaymentProviders = [
  {
    provide: INITIATE_LOANS_PAYMENT_JOURNEY_PAYMENT_ORDER_BASE_PATH,
    useExisting: APP_PAYMENT_ORDER_BASE_PATH,
  },
  {
    provide: INITIATE_LOANS_PAYMENT_JOURNEY_ARRANGEMENT_MANAGER_BASE_PATH,
    useExisting: APP_ARRANGEMENT_MANAGER_BASE_PATH,
  },
  {
    provide: INITIATE_LOANS_PAYMENT_JOURNEY_PAYMENT_TEMPLATE_BASE_PATH,
    useExisting: APP_PAYMENT_ORDER_BASE_PATH,
  },
  {
    provide: INITIATE_LOANS_PAYMENT_JOURNEY_CONTACT_MANAGER_BASE_PATH,
    useExisting: APP_CONTACT_MANAGER_BASE_PATH,
  },
  {
    provide: INITIATE_LOANS_PAYMENT_JOURNEY_PAYMENT_ORDER_A2A_BASE_PATH,
    useExisting: APP_PAYMENT_ORDER_A2A_BASE_PATH,
  },
  {
    provide: INITIATE_LOANS_PAYMENT_JOURNEY_PAYMENT_ORDER_OPTIONS_BASE_PATH,
    useExisting: APP_PAYMENT_ORDER_OPTIONS_BASE_PATH,
  },
  {
    provide: INITIATE_LOANS_PAYMENT_JOURNEY_ACCESS_CONTROL_BASE_PATH,
    useExisting: APP_ACCESS_CONTROL_BASE_PATH,
  },
];
