export enum ExternalAccountStatus {
  PERMANENT_FAILURE = 'PERMANENT_FAILURE',
  TEMPORARY_FAILURE = 'TEMPORARY_FAILURE',
  USER_ACTION_REQUIRED = 'USER_ACTION_REQUIRED',
  MULTI_FACTOR_AUTH_REQUIRED = 'MULTI_FACTOR_AUTH_REQUIRED',
  CREDENTIALS_UPDATE_REQUIRED = 'CREDENTIALS_UPDATE_REQUIRED',
  USER_ACTION_AND_CREDENTIALS_UPDATE_REQUIRED = 'USER_ACTION_AND_CREDENTIALS_UPDATE_REQUIRED',
  UNKNOWN = 'UNKNOWN',
}
